### ISSUE TITLE
Web component attributes not getting passed down

### ISSUE THREAD

**Issue by mnemanja** [LukasBombach/react-web-component#7]
How are attributes envisioned to be passed to the react component?
Are you perhaps using events to pass data to your web component rather than via event or attributes?

For example I could use lifecycle event `webComponentConstructed` and get the web component as a dom element there, and then do something like this:
```
webComponentConstructed(el) {
  console.log(el.attributes); // Returns an array of attributes
}
```

But could this be passed to react components `props` instead? I think it would make for a nicer integration. 

Do you think this makes sense?

**Comment by eriklharper** [comment]
Also think that this is a very less-than-ideal way to work with the custom element attributes.  Would be great if we could figure out a way to have these attrs pass down as props to the component.

**Comment by ctestama** [comment]
We're having the same issue. We want to create a bundle where our react components are registered as web components, however the props will not be known at bundle-time. I've also looked at this library: https://www.npmjs.com/package/web-react-components

That one passes the attributes to props just fine. It does not work with CSS modules though, while this module does. Not sure which would be the greater effort, to add the feature talked about here, or modify web-react-components to work with react-web-component-style-loader.

**Comment by dsuwirya** [comment]
It's been almost a year, is there any plan to fix this - please? This is very much needed. Thanks.

**Comment by caugello** [comment]
@LukasBombach any plans for this in the near future ?

**Comment by mnemanja** [comment]
Looks like this project has been dead for couple of years now.
