### ISSUE TITLE
Web components v1 and more

### ISSUE THREAD

**Issue by magnusjt** [LukasBombach/react-web-component#9]
Hey! Love this library..

I wanted to make it work with the v1 version of web components since that's what will be supported in the future. Actually I wanted to make a pull request, but then I saw there was a rewrite on the way already. 

Anyway, I made a gist that works with web components v1 that also has a fallback to work without shadow dom (even without polyfilling it):

https://gist.github.com/magnusjt/32250b89bbc3a529c413f1fc8cc256f8

If this is interesting, I can make a pull request out of it.

**Comment by dgreene1** [comment]
@magnusjt now that this library has a flag for turning off the Shadow DOM stuff, have considered using it again instead of your gist?

Also, since I just started learning about creating web components, I’m interested in what your experiences have been with converting react components into web components?

**Comment by magnusjt** [comment]
@dgreene1  I haven't checked this library out lately, but I see they've added support for v1 now. That's good. 

All in all, the web component experience has been pretty bad. The spec has changed a lot over the years. v0 was only implemented by chrome. v1 is still not implemented everywhere, and the polyfills are slow and buggy.

In my use case I wanted to use web components as a method for embedding react components inside an existing app. The only part of web components I found usable in that regard was custom elements. Shadow dom just recently got support in firefox, and I remember that I found the polyfill to be unusable. Also, many react libraries make assumptions about the dom that aren't true with shadow dom. So I ended up taking out shadow dom and manually scoping the css instead (as in the gist). 

The next thing I wanted to do was to make this work with create-react-app. I first did this by ejecting, but I recently made a custom react-scripts version for it instead (https://www.npmjs.com/package/@tfso/react-scripts-webcomponent and github: https://github.com/tfso/create-react-webcomponent/tree/custom). The react-scripts version has a build setup that puts everything in one file (including css), so it can be easily included in other apps. It also includes a minimal template with the setup required.

I guess the ultimate dream would be to package many small, independent web components with a react-app running inside. I haven't figured out how to do this yet, since each one of those components would have to include a separate copy of react, and will be huge as a result. The solution I've used for now is to put multiple web components in the same build.

I guess you could easily achieve the same thing without custom elements though, so not sure if it's worth it.

**Comment by dgreene1** [comment]
Thank you @magnusjt for the input. I’m going to give the same thing a shot (putting react components into an existing app) so if I get the chance, I’ll let you know what I find. By the way, I believe this issue can be closed now since the original issue has been solved by #10

**Comment by magnusjt** [comment]
That's great, hope to hear your experience as well :) I'll close the issue.
